services:
  - type: web
    name: d2mart
    runtime: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    disk:
      name: d2mart-data
      mountPath: /data
      sizeGB: 1
